[book]
authors = ["Defender"]
language = "en"
multilingual = false
src = "src"
title = "ğŸ¤ In Good Faith: A Handbook ğŸ­"

[output.html]
edit-url-template = "https://github.com/DefenderOfBasic/in-good-faith-handbook/edit/main/{path}"

[output.html.print]
enable = false 

[output.html.fold]
enable = true
level = 0 